### ISSUE TITLE
help@butterknifecrew.kr 메일 포워딩 목록 추가

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#100]
현재 버터나이프크루 대표 이메일 주소에 진저티 이메일이 포함되어 있지 않은 것으로 보이는데요. 
12/20 공개 후에는 기자 또는 외부에서 문의가 많이 올 것으로 예상됩니다.
대표 메일(help@butterknifecrew.kr) 포워딩 목록에 진저티 메일 주소(young@gingertproject.co.kr)를 추가해주세요.

**Comment by dalikim** [comment]
@anne-parti 대표메일 추가했고요. young@gingertproject.co.kr 안나님도 그룹 소유자로 등록했습니다. ^^ 앞으로 시일이 얼마 남지않아 관리할 것 없겠지만 잘 부탁드려요.

확인하고 이상 없으면 닫아주세요.

**Comment by anne-parti** [comment]
메일 포워딩 확인했습니다~
