### ISSUE TITLE
GNB 변경

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#102]
https://app.moqups.com/1Uzqb5b1rA/view/page/a47c1b80f

**Comment by anne-parti** [comment]
1. 기능은 정상 동작합니다. 
2. 레셈님이 디자인 이렇게 수정해주셨는데요. https://zpl.io/bA5LDJx
모바일 이슈도 있고 급한건 아니라 추후논의 라벨 달고 닫습니다.
