### ISSUE TITLE
추가 회원가입 컨트롤러에서 막기

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#103]
https://app.moqups.com/1Uzqb5b1rA/view/page/acf303d8a

**Comment by anne-parti** [comment]
@iamswain25 
1. GNB에서 회원가입만 눌러도 회원가입 불가 메시지가 뜨네요. 진저티에 여쭤보고 아예 회원가입 버튼을 뺄까봐요..
2. 소셜 로그인은 제가 구글밖에 남은 계정이 없어서 한 번만 테스트 했는데 비가입 계정으로 로그인 시도 시 이메일 로그인 페이지로 이동하는게 맞나요? 로그인 페이지(방식 선택하는)로 이동할 수 있다면 수정 부탁드립니다. 별도 메시지도 표시할 수 있으면 좋을 것 같아요. 지금은 그냥 로그인 오류처럼 보입니다. 
3. 혹시 회원 탈퇴나 관리자계정에서 삭제 가능한가요? 다른 소셜 로그인도 확인해봐야하는데 확인 가능한 계정이 없습니다(이미 모두 가입해서..) @dalikim

**Comment by anne-parti** [comment]
@iamswain25 
가입하지 않은 소셜 계정으로 로그인 시 어떻게 동작하도록 되어 있나요? 
제가 테스트해본 결과는 이렇습니다. 
1. 페이스북 -- 페이스북 페이지에서 에러 알림 뜸 '앱을 사용할 수 없음: 회원님이 사용하려는 앱은 사용이 불가능하거나 액세스가 제한되었습니다.' 
2. 구글 -- 이메일 로그인 페이지로 이동 + 아이디, 비밀번호를 확인하세요 메시지 표시됨 
3. 네이버 -- 이메일 로그인 페이지로 이동 + 아이디, 비밀번호를 확인하세요 메시지 표시됨
4. 카카오 -- 505 error 페이지 표시됨 

2, 3, 4 이메일 로그인 페이지 말고 로그인 방법 선택 페이지로 이동할 수 있나요?

**Comment by iamswain25** [comment]
이 건은 처리하는데 소요시간이 너무 길 것 같아요...

**Comment by iamswain25** [comment]
> 2, 3, 4 이메일 로그인 페이지 말고 로그인 방법 선택 페이지로 이동할 수 있나요?

현재 소셜 포함 이메일 로그인도 실패시 모두 `/email-login.do?login_error=1` 로 가게 되어 있습니다.
이걸 로그인 방법 선택 페이지로 돌릴 시 이메일 비번 잘못 넣어도 선택 페이지로 가게 되어서. 그냥 놔두는게 어떨까 합니다.
