### ISSUE TITLE
정책살롱 리스트 화면 변경

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#104]
- 정책살롱 명칭 변경 
- 내 버터보드 로그인 없을 시 보이지 않기
- 문화살롱과 비슷하게 퍼블

**Comment by anne-parti** [comment]
@iamswain25 정책살롱 타임라인 하단 이미지 변경해주세요
가이드: https://zpl.io/bA5LDJx (**레셈님 코멘트 확인 필요**)

**Comment by anne-parti** [comment]
@iamswain25 하단 이미지 가운데로 정렬해주세요.

**Comment by anne-parti** [comment]
확인했습니다!
