### ISSUE TITLE
관리자 권한 및 관리

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#105]
https://docs.google.com/spreadsheets/d/1LDiOQVGpTARVAP3Oqhzsm1GVSLs11esX0vo-FzynFMg/edit?usp=sharing

**Comment by anne-parti** [comment]
@iamswain25 문화살롱 프로젝트 쓰기 버튼도 관리자 계정(+가능하다면 운영진 권한 계정)에만 노출되도록 수정해주세요.

**Comment by anne-parti** [comment]
테스트 서버에서 확인했습니다.
