### ISSUE TITLE
문화살롱 - 상세 페이지에서 제목 모두 표시

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#109]
https://butterknifecrew.kr/salon.do?id=178
이 프로젝트처럼 제목이 길 경우에 상세 페이지 제목(커버) 영역에서 제목이 .. 처리되어 보이지 않는데요. 
제목이 길어도 모두 표시되도록 수정해주세요.

**Comment by iamswain25** [comment]
커버 페이지 영역이 1140 * 296 px로 확정되어 있어서 제목 다 보이게 모두 표시 될 시 이미지 밖으로 넘어가게 일단 처리할게요

**Comment by anne-parti** [comment]
@iamswain25 
1. 제목 길 경우 이렇게 표시되는데 수정된거죠? https://dev.butterknifecrew.kr/salon.do?id=210
2. 제목 영역 우측에 여백을 주어야할 것 같아요. 제목이 길 경우 제목 영역에 붙어 보입니다. 이부분 가이드 별도로 필요하신가요? (위에 남긴 링크에서 피씨버전 확인해주세요. 모바일 버전은 스크린샷 첨부합니다)
<img width="376" alt="스크린샷 2019-12-17 오후 1 07 21" src="https://user-images.githubusercontent.com/55128558/70964173-37d0bd00-20ce-11ea-8e11-18066c33ed41.png">

**Comment by iamswain25** [comment]
1. 네 제목 다 보입니다. 제목 길 경우 사진이 어떻게 보일지는 조정을 해봐야 할 것 같아요.
2. 우측에 16px 줄게요

**Comment by anne-parti** [comment]
테스트 서버에서 확인했습니다.
