### ISSUE TITLE
문화살롱 - 프로젝트 목록 오류  

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#112]
1. 문화살롱 페이지 프로젝트 목록에 프로젝트가 10개만 표시됩니다. 프로젝트 목록에 등록한 프로젝트가 모두 노출되도록 수정해주세요. 
2. 프로젝트 순서는 랜덤으로 노출돼야합니다. 현재는 등록 순으로 노출되네요. 수정 부탁드립니다.

**Comment by anne-parti** [comment]
@iamswain25 이 부분 수정되면 문화살롱 부분만 먼저 실서버 배포할 수 있을까요? 등록한 글 수정하려면 목록에 전부 노출되어야 합니다.

**Comment by iamswain25** [comment]
> @iamswain25 이 부분 수정되면 문화살롱 부분만 먼저 실서버 배포할 수 있을까요? 등록한 글 수정하려면 목록에 전부 노출되어야 합니다.

https://butterknifecrew.kr/salon-list.do?page=2 이렇게 접속해 보실래요? 서로 엮여 있어서 부분배포가 조금 어렵습니다.. @anne-parti

**Comment by anne-parti** [comment]
@iamswain25 
1. 개수 이슈는 확인했습니다. (12개에서 까지 업로드) 실서버 배포되면 다시 확인할게요
2. 프로젝트가 목록에 노출되는 순서는 아직 최신순으로 보여요. 페이지 접속시마다 랜덤으로 노출되도록 수정해주세요.

**Comment by anne-parti** [comment]
@iamswain25
1. 메인 페이지 문화살롱 영역은 랜덤으로 나오는거 확인했습니다. 👍
2. 문화살롱 페이지(/content) 내 목록은 아직 등록순대로 나오는데요. 이 페이지도 목록 순서가 랜덤으로 나오도록 수정해주세요.

**Comment by anne-parti** [comment]
문화살롱 페이지 내에서도 목록 랜덤으로 노출되는 것 확인했습니다~!
