### ISSUE TITLE
문화살롱 - 목록 페이지 모바일 디자인 적용

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#113]
1. 문화살롱 목록 페이지 모바일 버전 디자인 가이드 적용해주세요. 
디자인 가이드: https://zpl.io/Vqk4ALm

2. 목록 썸네일이 썸네일의 좌측 상단 부분만 크롭되어 표시됩니다. 이 부분도 수정 부탁드려요.

**Comment by iamswain25** [comment]
아 배경화면 약간 까맣게 들어가는거 모바일은 적용을 안했군요 ㅜㅜ

**Comment by anne-parti** [comment]
> 아 배경화면 약간 까맣게 들어가는거 모바일은 적용을 안했군요 ㅜㅜ

네 그리고 소개 부분 타이틀 영역이랑 텍스트 크기 이런 게 적용이 안된 것 같아요. 
전체적으로 한 번 확인 부탁드려요! 감사합니다~

**Comment by iamswain25** [comment]
아 안된게 좀 많았네요... 디자인 눈이 없어서 하다가 다 한줄 알았나봐요 😂

**Comment by anne-parti** [comment]
확인했고 다른 이슈랑 겹치는 부분도 있어서 클로즈합니다.
