### ISSUE TITLE
문화살롱 - 페이지 주소 변경

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#115]
문화살롱 페이지 주소를 기존의 /salon에서 /contents로 변경해주세요.

**Comment by iamswain25** [comment]
/content-list.do
/content.do?id=176
/content-edit.do?id=176
/content-new.do
이렇게 단수형으로 해도 될까요?
@anne-parti

**Comment by anne-parti** [comment]
주소 변경 확인했습니다.
