### ISSUE TITLE
수정 카운트 수를 테이블에 필드 추가하여 REVISION_CNT 로 넣는다.

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#12]
현재 YES_CNT에 들어간다.
디비 건드리기 겁나서 원래 필드 활용했지만,
달리님이 정명을 원하신다.

**Comment by iamswain25** [comment]
@dalikim 기능에 영향이 없는데, 이거 꼭 해야할까요?

**Comment by dalikim** [comment]
> @dalikim 기능에 영향이 없는데, 이거 꼭 해야할까요?

"꼭"은 아니네요. 대안은 뭘까요? 이 이슈를 drop하는 것일까요?

**Comment by iamswain25** [comment]
@dalikim 네, 버터보드를 demox에 통합하지 않는 이상 drop했으면 좋겠습니다. `ButterService.java` 안에 
```
statsRepository.increaseYesOpinion(butter.getId()); // 수정횟수 증가
```
이런식으로 코멘트는 되어 있습니다.

**Comment by dalikim** [comment]
네 좋습니다. 제가 닫을께요.
