### ISSUE TITLE
문화살롱 - 문화살롱 목록 카드에 공감이 2자리 수 이상일 경우 레이아웃 깨짐

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#123]
문화살롱 목록 카드에 공감 개수가 2자리 이상일 경우 공감 nn 개 박스 레이아웃이 깨집니다. 
공감 개수가 늘어나도 박스 레이아웃이 깨지지 않도록 수정 부탁드립니다. 
<img width="373" alt="스크린샷 2020-02-20 오후 5 35 38" src="https://user-images.githubusercontent.com/55128558/74915453-96385580-5407-11ea-9cd0-39fe725163b4.png">

**Comment by anne-parti** [comment]
@iamswain25 
2자리 이상일 때 '개' 가 잘려서 표시되지 않는데요. 
공감 버튼 크기를 가변으로 바꿀 수 있나요? 숫자 단위가 커지면 공감 버튼 길이도 늘어나도록이요.  
(크리티컬한 건 아니라 나중에 논의해봐요~)

**Comment by iamswain25** [comment]
> @iamswain25
> 2자리 이상일 때 '개' 가 잘려서 표시되지 않는데요.
> 공감 버튼 크기를 가변으로 바꿀 수 있나요? 숫자 단위가 커지면 공감 버튼 길이도 늘어나도록이요.
> (크리티컬한 건 아니라 나중에 논의해봐요~)

네 그렇게 할게요.

**Comment by anne-parti** [comment]
확인했습니다. 감사합니다 :+1:
