### ISSUE TITLE
일부 크루의 이름이 ??표로 표시됩니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#27]

**Comment by iamswain25** [comment]
utf8mb4로 디비 이모지 들어가는 것 확인, 디비에 ??라고 적혀있는 이름 두건 확인

**Comment by dalikim** [comment]
> utf8mb4로 디비 이모지 들어가는 것 확인, 디비에 ??라고 적혀있는 이름 두건 확인

@iamswain25  며칠 업데이트 된 것인가요? utf8mb4 작업 전인가요?

**Comment by dalikim** [comment]
> utf8mb4로 디비 이모지 들어가는 것 확인, 디비에 ??라고

**Comment by iamswain25** [comment]
소스랑 관계없이 디비 문제 였습니다. 달리님이 디비 작업 하시고 나서 저는 어제 이모지 들어가는것 local, staging 모두 확인했습니다. @dalikim

**Comment by dalikim** [comment]
> 소스랑 관계없이 디비 문제 였습니다. 달리님이 디비 작업 하시고 나서 저는 어제 이모지 들어가는것 local, staging 모두 확인했습니다. @dalikim

@iamswain25 

1. 네. demosx가 utf8mb4 고려가 없어서 처음 설치 후에 문제가 있었고요. 이건 demosx를 손봐야겠어요. demosx 레포지토리에 이슈로 남겨 주실래요? 

2. 추후 utf8mb4작업했는데요. ??표 들어간 사용자 2명이 언제일지 알면 확실할 것 같아 여쭤봤습니다. 확실하다 하시니 이제 알 필요는 없겠구요.

3. ??로 들어간 user 정보는 복원할 방법이 있을까요?

**Comment by dalikim** [comment]
@iamswain25 스스로 이름을 바꿀 수 있으니 상관없기도 하겠군요.

**Comment by iamswain25** [comment]
1. 스키마 세팅만 utf8mb4로 하면 되니 README.md에 추가만 하면 되지 않을까요? 소스랑 관련이 없지 싶네요. 이슈는 남기겠습니다.
1. 각각 9월 2일, 9월 8일입니다.
1. 안나님, 수진님 아이디인데요. 어떤 분이 디비에 직접 들어가 수정하신 느낌이 있습니다. ㅎㅎ 안그래도 안나님게 이야기 드리고 삭제하려고 했어요.

**Comment by dalikim** [comment]
> 1. 스키마 세팅만 utf8mb4로 하면 되니 README.md에 추가만 하면 되지 않을까요? 소스랑 관련이 없지 싶네요. 이슈는 남기겠습니다.

스키마 뿐만 아니라 테이블 설정을 바꿔야합니다.  flyway 등을 써서 강제하는 식은 어떨까 합니다. 그래서 이슈가 필요하다 생각했습니다.

> 2. 각각 9월 2일, 9월 8일입니다.

네 확인 감사합니다.

> 3. 안나님, 수진님 아이디인데요. 어떤 분이 디비에 직접 들어가 수정하신 느낌이 있습니다. ㅎㅎ 안그래도 안나님게 이야기 드리고 삭제하려고 했어요.

네 그럼 이 이슈는 닫아도 되겠네요. 감사합니다.

**Comment by dalikim** [comment]
@iamswain25 https://github.com/parti-coop/govcraft/blob/f5c0925b3cf2561759cedb7250a31f4c5a37b7c3/db/schema.rb#L39 이런 설정이 필요할까 싶어요.
