### ISSUE TITLE
수정페이지 (이전페이지와 같이 비교?)

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#3]
- mergerly와 simplemde 같이 써서 수정시 편리하게
- 자잘한 수정, 큰 수정 확인필요.

기획 어떻게 바뀌는가 중요.

**Comment by dalikim** [comment]
저장 직전에 conflict 경우를 판단해서 conflict경우만 mergerly를 쓰면 어떤가 싶고요. 보통 수정패이지는 simplemde를 써도 좋겠어요.

그리고 conflict는 다음주에 개발하시죠. 

(덧붙이는 의견으로 conflict는 복잡하게 판단말고 그냥 쓰기 form 불러온 문서 버전을 히든필드로 두었다가, 저장 직전에 최신 문서 버전과 비교해서 다르면 conflict 처리하면 해요)

**Comment by dalikim** [comment]
그리고 메이커가 아닌 일반 크루의 경우에는 본문의 내용과 변경 요약만 고칠 수 있습니다.
