### ISSUE TITLE
버터보드 레이블을 다듬습니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#30]
141, 144, 146번 가이드 보드를 별도 GNB로 만들기. 레이블은 '가이드'
 GNB 버터제안 -> 버터보드로 레이블 변경

**Comment by dalikim** [comment]
버터문서란 말을 모두 버터보드로 통일하면 어떨까 합니다. @kimboyhood @iamswain25 @ssinkjung

**Comment by dalikim** [comment]
버터 추가할때 "수정 내용"이란 말도 "발행 히스토리 내용"이런 말로 통일할까요? @iamswain25 @kimboyhood @ssinkjung @anne-parti

**Comment by boyhood-parti** [comment]
버터문서는 버터보드로, 수정 이력은 발행 히스토리로 통일하면 좋겠어요.

**Comment by iamswain25** [comment]
메이커일 경우 상단에 `내용 수정` 버튼이 하단의 `버터 추가하기` 버튼과 기능이 같은데, 레이블이 다릅니다. @kimboyhood

**Comment by iamswain25** [comment]
`버터보드 추가 중 다른 버터와 충돌이 났습니다.` alert 메시지가 사용자에게 익숙하지 않은 문구라 에러로 받아들일 가능성 큼. @kimboyhood @anne-parti 다른 문구 혹시 있을지 알려주시면 감사하겠습니다.

**Comment by iamswain25** [comment]
내 버터보드가 없을 시 문구로 처리하는 방법? @anne-parti

**Comment by dalikim** [comment]
"거의 수정이 다 되었습니다. 최근에 OOO님이 추가한 버터를 합해주세요." 정도?

**Comment by anne-parti** [comment]
> 내 버터보드가 없을 시 문구로 처리하는 방법? @anne-parti

보드 목록 영역에 텍스트로 메이커로 추가된 버터보드가 없다고 안내하면 좋겠습니다. 

메이커로 참여한 버터보드가 없습니다
아직 메이커로 참여한 버터보드가 없습니다 
참여한 버터보드가 없습니다
아직 참여한 버터보드가 없습니다 
등.. 

문구는 @kimboyhood 님도 함께 고민해주세요.

**Comment by anne-parti** [comment]
> `버터보드 추가 중 다른 버터와 충돌이 났습니다.` alert 메시지가 사용자에게 익숙하지 않은 문구라 에러로 받아들일 가능성 큼. @kimboyhood @anne-parti 다른 문구 혹시 있을지 알려주시면 감사하겠습니다.

버터보드 추가 중 다른 버터보드와 충돌이 일어났습니다. '확인'을 눌러 수정을 완료하세요. 
이런 문구는 어떨까요? @kimboyhood

**Comment by boyhood-parti** [comment]
> 메이커일 경우 상단에 `내용 수정` 버튼이 하단의 `버터 추가하기` 버튼과 기능이 같은데, 레이블이 다릅니다. @kimboyhood

버터 추가하기로 통일하면 어떨까요? 내용 수정과 버터 추가의 개념이 서로 다를 때 정했던 레이블인 것 같네요.

**Comment by boyhood-parti** [comment]
> > 내 버터보드가 없을 시 문구로 처리하는 방법? @anne-parti
> 
> 보드 목록 영역에 텍스트로 메이커로 추가된 버터보드가 없다고 안내하면 좋겠습니다.
> 
> 메이커로 참여한 버터보드가 없습니다
> 아직 메이커로 참여한 버터보드가 없습니다
> 참여한 버터보드가 없습니다
> 아직 참여한 버터보드가 없습니다
> 등..
> 
> 문구는 @kimboyhood 님도 함께 고민해주세요.

새로운 버터보드를 개설해보세요.

같은 버터보드를 개설하게 유도하는 문구는 어떨까요? 예상치보다 버터보드 개설 수가 적은 상황이라 버터보드가 조금 더 많아지는 게 좋을 것 같아요.

**Comment by boyhood-parti** [comment]
> > `버터보드 추가 중 다른 버터와 충돌이 났습니다.` alert 메시지가 사용자에게 익숙하지 않은 문구라 에러로 받아들일 가능성 큼. @kimboyhood @anne-parti 다른 문구 혹시 있을지 알려주시면 감사하겠습니다.
> 
> 버터보드 추가 중 다른 버터보드와 충돌이 일어났습니다. '확인'을 눌러 수정을 완료하세요.
> 이런 문구는 어떨까요? @kimboyhood

다른 사람과 동시에 버터를 추가했습니다. '확인'을 눌러 다시 버터를 추가해주세요.
충돌이라는 말을 빼면 어떨까요? @iamswain25 @anne-parti

**Comment by anne-parti** [comment]
> > > 내 버터보드가 없을 시 문구로 처리하는 방법? @anne-parti
> > 
> > 
> > 보드 목록 영역에 텍스트로 메이커로 추가된 버터보드가 없다고 안내하면 좋겠습니다.
> > 메이커로 참여한 버터보드가 없습니다
> > 아직 메이커로 참여한 버터보드가 없습니다
> > 참여한 버터보드가 없습니다
> > 아직 참여한 버터보드가 없습니다
> > 등..
> > 문구는 @kimboyhood 님도 함께 고민해주세요.
> 
> 새로운 버터보드를 개설해보세요.
> 
> 같은 버터보드를 개설하게 유도하는 문구는 어떨까요? 예상치보다 버터보드 개설 수가 적은 상황이라 버터보드가 조금 더 많아지는 게 좋을 것 같아요.

@iamswain25 이 내용 적용 안된것 같은데 확인 부탁드려요. 
@dalikim 비로그인 상태에서 내 버터보드 (0) 으로 표시되는 건 괜찮을까요? 비로그인 상태에서는 내 버터보드 항목을 숨기거나 옆에 로그인 버튼을 추가하는건 어떤가요?

**Comment by dalikim** [comment]
> > > > 내 버터보드가 없을 시 문구로 처리하는 방법? @anne-parti
> > > 
> > > 
> > > 보드 목록 영역에 텍스트로 메이커로 추가된 버터보드가 없다고 안내하면 좋겠습니다.
> > > 메이커로 참여한 버터보드가 없습니다
> > > 아직 메이커로 참여한 버터보드가 없습니다
> > > 참여한 버터보드가 없습니다
> > > 아직 참여한 버터보드가 없습니다
> > > 등..
> > > 문구는 @kimboyhood 님도 함께 고민해주세요.
> > 
> > 
> > 새로운 버터보드를 개설해보세요.
> > 같은 버터보드를 개설하게 유도하는 문구는 어떨까요? 예상치보다 버터보드 개설 수가 적은 상황이라 버터보드가 조금 더 많아지는 게 좋을 것 같아요.
> 
> @iamswain25 이 내용 적용 안된것 같은데 확인 부탁드려요.
> @dalikim 비로그인 상태에서 내 버터보드 (0) 으로 표시되는 건 괜찮을까요? 비로그인 상태에서는 내 버터보드 항목을 숨기거나 옆에 로그인 버튼을 추가하는건 어떤가요?

제 생각엔 내 버터보드 0을 지우고 개설 안내 박스를 옆으로 넓히는게 좋겠습니다
