### ISSUE TITLE
발행 이력을 비교할 때 마지막 줄이 반 가려 잘 보이지 않음

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#33]
마지막 줄이 잘 보이지 않는다.
code mirror 소스 다른버전 중복됐는지 확인

**Comment by iamswain25** [comment]
버전 중복은 없지만, 여전히 이전 기록의 마지막 줄이 잘 스크롤바에 막혀 잘 보이지 않는다. 현재 기록도 마우스 스크롤은 잘 들지 않고, 키보드 커서로 이동하면 보인다. 이전 기록은 키보드로도 반 가려져 있는데, 원소스 자체의 문제일 듯 하다.

**Comment by dalikim** [comment]
혹시 마지막에 줄바꿈을 두번 넣어 에디터를 보여주고,
저장할때 trim하는 방식은 어떨까나요? @iamswain25

**Comment by dalikim** [comment]
@iamswain25 어제 시간이 있어서 고민해 봤는데요. mergely를 drop하고 최신 codemirror를 써서 codemirror addon merge를 이용하는 식으로 구현해 봤습니다. 

대신 simplemde가 아주 예전 codemirror에 dependency가 있는지라. easymde 2.8.0 https://github.com/Ionaru/easy-markdown-editor/ 라는 걸로 simplemde를 교체했습니다. simplemde를 fork하고 codemirror 5.48.4를 쓰고 있더군요. 

있다 PR 날리면서 여기에 연결할께요.
