### ISSUE TITLE
작은 버터 추가는 발행이력에서 숨겨서 중요한 발행이력만 보이게 합니다.

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#34]
작은 버터 추가 발행이력은 버터문서 상세에서 현재는 다 같이 보이나,
가치가 떨어지는 정보이니, 더보기 버튼 누르거나 체크박스 토글해야 보이게 하는게 어떨지요.

@kimboyhood 의견 바랍니다.
이해가 안가시면 화상으로 설명 드리겠습니다.

**Comment by iamswain25** [comment]
#10 과 살짝 충돌납니다. @dalikim AJAX 페이징하고 이 이슈는 드롭이 어떨까요?

**Comment by dalikim** [comment]
우선은 드롭하지요
