### ISSUE TITLE
에디터가 IE 등 다양한 브라우저에서 작동되게 합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#37]

**Comment by iamswain25** [comment]
#49 안나님이랑 브라우저스택을 이용해 IE 테스트 중 맥북에서 한글이 써지지 않아 크롬으로 진행했습니다. 제 리눅스에서는 영어/한글 모두 써지지 않았습니다.

**Comment by dalikim** [comment]
슬로워크에 우선 테스트용 PC 혹은 노트북을 빌려 보겠습니다.
