### ISSUE TITLE
슬렉 이벤트 후크 넣기

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#4]
- [x] url과 channel 넣어 연동
- [x] 저장 시 포스트
- [x] 수정 시 포스트
- [ ] 댓글 시 포스트
- [x] 삭제 시 포스트
- [x] 메시지에 링크 포함
- [x] 띄워쓰기 먹지 않음
- [x] 아이콘 이름 추가
- [x] type=hidden에서 display:none으로 변경

**Comment by dalikim** [comment]
그냥 DB 콘솔에서 입력하는거죠?

**Comment by iamswain25** [comment]
@dalikim 디비 콘솔도 괜찮습니다. 위에서는 크롬 개발자 콘솔로 전역변수 넣는 방법 생각했습니다.
