### ISSUE TITLE
버터보드 모바일 지원을 합니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#43]

**Comment by iamswain25** [comment]
안나님이 레셈님한테 디자인 요청해서 진행하기로 했습니다.

**Comment by dalikim** [comment]
@kimboyhood @anne-parti  오늘 오후까지 함께 테스트 부탁드립니다.

**Comment by boyhood-parti** [comment]
@dalikim @iamswain25 이번 2.0.1 버전에서는 모바일 디자인 적용은 하지 않고 릴리즈하기로 안나님과 이야기했습니다. 모바일 디자인 적용은 다음 마일스톤 때 적용하는 것으로요.

**Comment by iamswain25** [comment]
디자인 퍼블리싱
