### ISSUE TITLE
테스트서버에서 소셜 로그인 설정을 합니다.

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#44]

**Comment by iamswain25** [comment]
- @dalikim 네이버 빼고, 페북, 네이버, 카톡은 잘 되는데, 혹시 네이버를 연동해야할까요? "준비중입니다" 문구가 뜹니다. 
- 어제 공유화면에서 클릭 하셨을 때 잘 안되었던 것 같은데, 혹시나 테스트서버와 실서버 URL이 달라서 그런건 아닐지 @anne-parti 안나님과 테스트 한 번 더 해볼게요.

**Comment by dalikim** [comment]
> * @dalikim 네이버 빼고, 페북, 네이버, 카톡은 잘 되는데, 혹시 네이버를 연동해야할까요? "준비중입니다" 문구가 뜹니다.

이건 다른 이슈로 뽑아주세요

> * 어제 공유화면에서 클릭 하셨을 때 잘 안되었던 것 같은데, 혹시나 테스트서버와 실서버 URL이 달라서 그런건 아닐지 @anne-parti 안나님과 테스트 한 번 더 해볼게요.

테스트서버에 키 설정을 안했어요. 요걸 이슈에서 다뤄야해요. 이건 페어해요.

**Comment by iamswain25** [comment]
테스트서버에 키 설정을 안했는데 지금 카톡 아이디로 로그인이 되는게 이해가 되지 않네요.
키 설정은 암호화 돼있는 `globals.properties`아닌가요?
@dalikim 달리님 캘린더 보니 빈 시간이 거의 없어서 페어 일정을 못 잡았습니다. 편한 시간으로 잡아서 초청해주세요

**Comment by iamswain25** [comment]
@dalikim 테스트 하니까 이해되네요. 회원가입하면 자동으로 실서버 이동해서 로그인합니다.

**Comment by iamswain25** [comment]
@dalikim 테스트 서버 로그인 api 구글 설정만 남았는데 contact@parti.xyz 계정 로그인 하니 폰으로 인증해야한다고 나오네요. 추가 개발자로 swain@parti.xyz 권한 승인바랍니다.

**Comment by anne-parti** [comment]
@iamswain25 네이버 로그인은 어떻게 하기로 되었나요? 네이버 로그인 시도 시 네이버로 이동 > 로그인 > 버터나이프크루 500 error 페이지로 이동합니다.

**Comment by iamswain25** [comment]
@anne-parti 혹시 실서버에서 시도 하셨나요? test서버는 저는 되는데, 아직 실서버는 적용하지 않았습니다. 실서버는 내일 배포하려고요.
