### ISSUE TITLE
IE 테스트를 할 방법을 찾습니다

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#49]
브라우저스택 한글 써지지 않아 다른 테스트 서비스 찾아야겠습니다.

안나님 맥북에서는 영어만 써지고
제 리눅스 컴퓨터는 복붙만 됩니다.

**Comment by iamswain25** [comment]
### 가상머신

- 윈도우 7, ie 11 테스트하는 virtualbox를 제공하네요.  https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by dalikim** [comment]
@anne-parti 윈도우10 가상머신을 시도해 볼까요? 전에 행정 일을 할때 가상머신 시도했다가 너무 느려서 drop했는데요. 세상 좋아졌으니 다시 시도해도. 

https://www.parallels.com/kr/products/desktop/trial/
