### ISSUE TITLE
사용자 아이콘 네모 -> 동그랗게 처리

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#50]
z-index 이슈 확인
가운데 사용자가 제일 위로 올라오면 안됨

**Comment by gjkimpam** [comment]
목록에서 동그랗게 보이는 것 확인했습니다. 그런데 목록에서만 동그랗게 처리하시는 것인지요? 
상세페이지 내 
- [ ] 왼쪽 측면의 메이커 리스트
- [ ] 하단의 '버터를 추가한 크루입니다'. 
- [ ] '히스토리'의 아이콘은 네모로 처리되어 있더라고요. 

![스크린샷 2019-10-30 오후 1 53 28](https://user-images.githubusercontent.com/35594166/67864116-06e7f900-fb1d-11e9-95d5-e8162957a783.png)
![스크린샷 2019-10-30 오후 1 55 29](https://user-images.githubusercontent.com/35594166/67864117-07808f80-fb1d-11e9-9fcc-550e4f777898.png)

**Comment by iamswain25** [comment]
크... 그렇네요 알려주셔서 감사합니다.
