### ISSUE TITLE
3명 초과하는 메이커 `+1` 호버하면 메이커 이름 보이게 처리

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#52]
메이커 여러명일 시 3명까지만 아이콘 보이고, 나머지는 상세에 들어가야 이름이 보이는데, 호버로 보일 수 있도록 처리.

**Comment by anne-parti** [comment]
@iamswain25 호버 시 닉네임이 더 빠르게 뜨도록 조정 가능한가요?

**Comment by iamswain25** [comment]
> @iamswain25 호버 시 닉네임이 더 빠르게 뜨도록 조정 가능한가요?

현재 html기본 속성으로 넣었는데, 다른 라이브러리 쓰면 가능합니다. 우선순위 정해주시면 맞춰서 개발 가능합니다. @anne-parti

**Comment by anne-parti** [comment]
@iamswain25 정상적으로 동작하니 우선순위 높은건 아니에요. @gjkimpam @dalikim 확인해보시고 클로즈해주세요.

**Comment by dalikim** [comment]
> @iamswain25 정상적으로 동작하니 우선순위 높은건 아니에요. @gjkimpam @dalikim 확인해보시고 클로즈해주세요.

저는 이 상태로 마무리하고 싶습니다.

**Comment by gjkimpam** [comment]
저도 정상 작동하는 것 확인했습니다. 
제가 close 권한이 없네요. 다른 분이 close 해주시면 되겠습니다.
