### ISSUE TITLE
보드와 슬랙 채널 알림 연결

### ISSUE THREAD

**Issue by boyhood-parti** [parti-coop/demosx-buttercon#53]
보드의 큰 버터 수정 시, 댓글 작성 시 해당 슬랙 채널로 알림이 갑니다.
슬랙채널명/보드명
- [x] 성인대상_성평등교육 / 성인대상_성평등교육
- [x] 지역청년 / 버터나이프크루의 프랜차이즈화
- [x] 페미디어 / 성평등한 미디어 제작을 위한 가이드라인 제안
- [x] 직장평평이
 / 성평등한 직장문화를 위한 현존 제도의 실효성 검토/평가
- [x] 건강하자 / 내 마음에도 이름이 있다.
- [x] job다행이다 
/ 이직자, 퇴직자의 새로운 일탐험 보장제도 (갭먼스)
- [x] 아파도괜찮아 / 유급병가 의무화 추진 제안
- [x] 버뮤다로컬페미 
/ 지역여성활동증진법
- [x] 으쓱으쓱_성평등교육 / 초등학생 성 평등 교육 의무화
- [x] 4u_비혼커뮤니티 / 다양한 삶을 위한 비혼클럽
- [x] 강이지_비혼여성의주거 / 비혼여성을 위한 주거정책
- [x] we-mate_동반자법
 / 'We mate(동반자법)' 입법을 허락하라
- [x] 여자혼자산다_1인여성비혼주거 / 지역에 사는 1인 여성의 주거 안전 보장 정책 제안
- [x] 긴박한집_여성1인가구와_안전 / 여성 1인가구 행복타운

**Comment by boyhood-parti** [comment]
@iamswain25 @dalikim 지난 해커톤에서 개설된 보드와 슬랙 채널 알림 연결이 필요할 것 같아요. 매칭해서 정리해봤습니다.

**Comment by iamswain25** [comment]
> @iamswain25 @dalikim 지난 해커톤에서 개설된 보드와 슬랙 채널 알림 연결이 필요할 것 같아요. 매칭해서 정리해봤습니다.

현재 기능은 완성되어 있습니다. 제가 그쪽 슬랙 워크스페이스에 접속해서 연결하면 될 것 같은데요. 소년님 혹시 데드라인이 있나요?

**Comment by dalikim** [comment]
@kimboyhood @iamswain25 두 분이 페어하면 어떨까요? 나중엔 @kimboyhood 님이 혼자 운영하실 수 있게요

**Comment by iamswain25** [comment]
@kimboyhood 캘린더 보냈습니다.

**Comment by boyhood-parti** [comment]
@iamswain25 네 11시에 뵐게요!

**Comment by boyhood-parti** [comment]
현재까지 개설된 보드와 채널은 연결 완료했습니다.

**Comment by dalikim** [comment]
@kimboyhood @iamswain25 혹시 보드 개설을 슬랙으로 알림받을 수 있을까요? @kimboyhood 나 운영하시는 분들이 슬랙 연결하게요.

**Comment by iamswain25** [comment]
> @kimboyhood @iamswain25 혹시 보드 개설을 슬랙으로 알림받을 수 있을까요? @kimboyhood 나 운영하시는 분들이 슬랙 연결하게요.

https://github.com/parti-coop/demosx-buttercon/blob/2943e1a0cb5bbd024c96e83caa6da180f42c0ae3/src/main/java/seoul/democracy/butter/service/ButterService.java#L103

등록화면에서도 개발자 콘솔창에 `$("#slack").show()` 쳐서 수정과 같이 알림이 가능합니다.

**Comment by iamswain25** [comment]
> 소년님이 진저티 쪽에 인수인계 가능하게 개발자 콘솔 입력 대신 2초내 제목 클릭 다섯번 이런거 만들까요?? @kimboyhood 

1. 특정 아이디로 로그인한 경우에는 슬랙 세팅할 수 있는 인풋 박스가 보드 상세 수정 화면에서 보이는 것
2. 새로운 보드가 생기면 알림을 관리자가 볼 수 있는 슬랙 알림 보내는 것

을 제안합니다 @kimboyhood @iamswain25 @anne-parti

**Comment by boyhood-parti** [comment]
> > 소년님이 진저티 쪽에 인수인계 가능하게 개발자 콘솔 입력 대신 2초내 제목 클릭 다섯번 이런거 만들까요?? @kimboyhood
> 
> 1. 특정 아이디로 로그인한 경우에는 슬랙 세팅할 수 있는 인풋 박스가 보드 상세 수정 화면에서 보이는 것
> 2. 새로운 보드가 생기면 알림을 관리자가 볼 수 있는 슬랙 알림 보내는 것
> 
> 을 제안합니다 @kimboyhood @iamswain25 @anne-parti

오늘 해커톤 백업 살롱(이번 주 수요일 추가 OT)에 대해 이야기 나눴는데요. 최대 5명 정도가 오신다고 하네요. 버터보드는 올해 사업기간동안에는 추가 개설될 가능성이 아주 낮아보입니다. 하나씩 눈으로 봐도 될 정도로요. 서원님이 제안해주신 것 중에 2. 새로운 보드가 생기면 알림을 관리자가 볼 수 있는 슬랙 알림 보내는 것은 필요없을 것 같아요. 1번 기능은 관리자 아이디에 추가하면 좋을 것 같은데, 이것도 추가로 슬랙 알림 세팅을 할 보드가 없을 것 같아 우선순위는 낮아보이네요. @iamswain25 @dalikim @anne-parti
