### ISSUE TITLE
메이커가 문서 수정 시 메이커 추가 폼에서 크루 검색이 안됨

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#57]
문서 생성 후 수정 페이지에서 메이커를 추가하려고 할때, 크루 이름 검색이 안됩니다. 수동으로 이름 추가할 경우에는 수정 버튼 동작이 안됩니다. (크롬, 사파리 동일)
<img width="447" alt="addmaker" src="https://user-images.githubusercontent.com/55128558/67838880-afa25280-fb35-11e9-81fc-37c84cd829a6.png">

**Comment by gjkimpam** [comment]
저는 검색이 됐어요. (크롬에서 확인)
![스크린샷 2019-10-30 오후 1 42 58](https://user-images.githubusercontent.com/35594166/67863177-51687600-fb1b-11e9-8312-a2c7c4c99ae6.png)

**Comment by iamswain25** [comment]
추가는 되는데, 수정이 안되네요 ㅜ
