### ISSUE TITLE
네이버 로그인 설정

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#59]
페어요청 드립니다. 500 에러가 뜨는데, logging이 안돼요.

**Comment by dalikim** [comment]
https://github.com/parti-coop/demosx-buttercon/blob/29d694d4c449957f55b51e0b3f22be1f9dec49c3/src/main/java/seoul/democracy/social/service/SocialAuthenticationProvider.java#L45

4dd4f4f7f5671232bfefa2d4370bd082262e37bb 10개월 전 커밋할 때는 naver에서 name (사람 이름)을 가져왔었나 보네요. 주로 관공서 대상으로 하는 플랫폼이라 생각해서 그랬나봐요.

버터나이프 크루는 네이버에 name을 열어달라고 요청하지 못했습니다. 제 생각에는 nickname을 가져오면 합니다.

```java

        if (authToken.getProvider().equals("naver")) {
            OAuth20Service service = socialService.naver();
            final OAuthRequest req = new OAuthRequest(Verb.GET, "https://openapi.naver.com/v1/nid/me");
            service.signRequest((OAuth2AccessToken) authToken.getToken(), req);
            try {
                final Response res = service.execute(req);
                Map<String, Object> map = JsonUtils.asStringToMap(res.getBody());
                Map<String, Object> mapResponse = (Map<String, Object>) map.get("response");
                id = mapResponse.get("id").toString();
                name = mapResponse.get("nickname").toString(); // <============= 여기
                photo = mapResponse.get("profile_image").toString();
            } catch (InterruptedException | ExecutionException | IOException e) {
                throw new UsernameNotFoundException("Unknown connectd account id");
            }
        }

```

**Comment by dalikim** [comment]
참고 삼아 네이버에 버터나이프크루 설정한 화면 보여 드립니다.

<img width="1352" alt="스크린샷 2019-10-31 21 36 14" src="https://user-images.githubusercontent.com/1650024/67947216-831a3380-fc26-11e9-9d17-1af0eb6ba71a.png">

**Comment by iamswain25** [comment]
에러메시지가 `500` 밖에 보이지 않고, 로깅이 찍히지 않아 헤맸습니다. ㅎㅎ 로깅 찍는 부분은 다음에 페어하며 물어볼게요.
