### ISSUE TITLE
버터 보드를 오래 열어 놓고 계속 수정해도 로그아웃 되지 않습니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#63]

**Comment by iamswain25** [comment]
https://github.com/parti-coop/demosx-buttercon/blob/29d694d4c449957f55b51e0b3f22be1f9dec49c3/src/main/resources/egovframework/spring/context-session.xml#L20

10시간 세션인데, 세션 끊기고 저장 누르면 ajax만 403 권한에러가 날 것 같아요. 어떻게 하면 좋을까요? @dalikim 
## 대안
1. 로그인이 api token으로 되면 페이지 새로고침 하지 않고도 재로그인 가능
1. 403 권한 에러시, 현재 창 내용 브라우저 저장하고, 새로 로그인. 새로운 버터보드 클릭하면 브라우저 저장 내용 자동 불러오기. <== 추천

**Comment by dalikim** [comment]
1. 세션 타임
세션 타임 아웃 403을 그냥 로그아웃 시키고 첫 페이지로 보내면서 얼럿 정도 띄우는게 적당 수준의 일감이라 생각해요. 오버스펙 말면 합니다

2. 보드에서 세션 아웃
혹시 에디터가 열리면 주기적으로 서버에 접속을 자동으로 하게 하는건 어때요?

**Comment by iamswain25** [comment]
10시간 세션이 엄청 기니, 걱정해야할 상황이 브라우저 열린채로 컴터가 휴면상태에 들어가는건데, 이 상황은 setInterval 로 해결이 힘들것 같네요. 오버스펙 하지 않고 세션을 24시간으로 늘릴까요? @dalikim

**Comment by dalikim** [comment]
> 10시간 세션이 엄청 기니, 걱정해야할 상황이 브라우저 열린채로 컴터가 휴면상태에 들어가는건데, 이 상황은 setInterval 로 해결이 힘들것 같네요. 오버스펙 하지 않고 세션을 24시간으로 늘릴까요? @dalikim

더하기해서 오류는 안나게 홈으로 redirect 가능할까요?

**Comment by iamswain25** [comment]
> > 10시간 세션이 엄청 기니, 걱정해야할 상황이 브라우저 열린채로 컴터가 휴면상태에 들어가는건데, 이 상황은 setInterval 로 해결이 힘들것 같네요. 오버스펙 하지 않고 세션을 24시간으로 늘릴까요? @dalikim
> 
> 더하기해서 오류는 안나게 홈으로 redirect 가능할까요?

에디터 열렸을 시 confirm띄워서 홈으로 redirect 시킬게요.

**Comment by dalikim** [comment]
> * 세션 타임
>   세션 타임 아웃 403을 그냥 로그아웃 시키고 첫 페이지로 보내면서 얼럿 정도 띄우는게 적당 수준의 일감이라 생각해요. 오버스펙 말면 합니다
> * 보드에서 세션 아웃
>   혹시 에디터가 열리면 주기적으로 서버에 접속을 자동으로 하게 하는건 어때요?

@iamswain25 보드 세션 아웃만을 위의 방법으로 막는건 오버스펙일까요? 403 세션 아웃을 홈으로 reditect하는건 전체 사이트 적용하고요

**Comment by iamswain25** [comment]
추가 요청 생길 시 다시 엽니다
