### ISSUE TITLE
버터 보드를 수정할 때 자동으로 임시 저장됩니다

### ISSUE THREAD

**Issue by dalikim** [parti-coop/demosx-buttercon#64]
보드 에디터를 열 때 임시 저장된게 있으면 기존 저장된 것을 불러올지 물어 봅니다

**Comment by iamswain25** [comment]
@dalikim 
confirm 써서 하려니 버터보드 수정이 애매하네요, 아래 로직 확인 바랍니다.

---
### 새로운 버터보드
기존 저장 불러옵니까?
- 예: 불러온다
- 취소: 기존 저장 지운다.

### 버터보드 수정
기존 저장 불러옵니까?
- 예: 불러온다
- 취소: 기존 저장 지운다.
