### ISSUE TITLE
메인 페이지 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#67]
2.0.1 릴리즈 후에 메인 페이지 수정이 필요합니다.
필요한 내용이 있으면 추가해주세요 @kimboyhood @dalikim 

- 정책 살롱 신청 안내 배너 삭제
- 버터보드 영역 추가 
- 기타..

**Comment by dalikim** [comment]
최소한으로 가면 어떨까요?

오프라인 살롱(아지트?) 일정 페이지가 있죠? @kimboyhood  
그거 링크랑, 보드의 최근 업데이트 같은건 어떨가요?

**Comment by boyhood-parti** [comment]
@dalikim @anne-parti 달리님 의견과 비슷한데요. 현재 페이지에서 아이디어를 6개에서 2개로 줄이고,
최근 업데이트된 버터보드를 추가하면 어떨까요? 위에서부터 정책살롱 참여하기(일정 페이지), 업데이트된 버터보드, 아이디어 순으로요.

**Comment by iamswain25** [comment]
https://app.moqups.com/1Uzqb5b1rA/view/page/a0890b8ca

- 버터보드 명칭 정책살롱으로 변경
- 가이드 빼고 랜덤으로 3개 보여주기
- 분문요약 첫 H1 이후로 보이기
  - 가이드, 행동강령 빼고
- 문화살롱도 랜덤으로 3개 보이기

**Comment by anne-parti** [comment]
논의 끝나서 이슈 닫습니다.
