### ISSUE TITLE
버터보드 본문 페이지에서 보이는 버터보드 텍스트에 인라인 링크를 넣습니다.

### ISSUE THREAD

**Issue by boyhood-parti** [parti-coop/demosx-buttercon#68]
<img width="1174" alt="스크린샷 2019-11-05 오후 8 25 07" src="https://user-images.githubusercontent.com/53370999/68204182-cac80300-000a-11ea-939d-691493075905.png">

이 이미지 상단에 보이는 버터보드 텍스트에 버터보드 리스트로 가는 링크(https://butterknifecrew.kr/butter-list.do)를 넣으면 어떨까요? 리스트로 돌아가고 싶을 때 자주 저 텍스트를 누르게 되네요.

**Comment by iamswain25** [comment]
좋은 아이디어 인것 같아요. 일주일 안에 한 번 더 2.0.3으로 실서버 적용할게요.
