### ISSUE TITLE
버터보드 본문에 #HELP 를 표시할 수 있습니다.

### ISSUE THREAD

**Issue by boyhood-parti** [parti-coop/demosx-buttercon#74]
본문 중 도움이 필요한 부분에 #HELP 를 표시에 더 눈에 띄게 할 수 있습니다.

**Comment by boyhood-parti** [comment]
@dalikim @iamswain25 이슈로 추가해봤습니다. 이번 주 금요일(11/15)이 버터보드 1차 완성을 마무리하는 데드라인이에요. 다음 주 부터 서로 피드백이 더 활발해지는 시기이지 않을까 싶습니다. 혹시 이번 주까지 개발이 가능할까요?

**Comment by iamswain25** [comment]
> @dalikim @iamswain25 이슈로 추가해봤습니다. 이번 주 금요일(11/15)이 버터보드 1차 완성을 마무리하는 데드라인이에요. 다음 주 부터 서로 피드백이 더 활발해지는 시기이지 않을까 싶습니다. 혹시 이번 주까지 개발이 가능할까요?

@kimboyhood 조금더 설명해주실수 있을까요? 지금 #HELP 쓰는 것에 어떤 시각적 효과가 추가되어야 하나요?

**Comment by boyhood-parti** [comment]
> > @dalikim @iamswain25 이슈로 추가해봤습니다. 이번 주 금요일(11/15)이 버터보드 1차 완성을 마무리하는 데드라인이에요. 다음 주 부터 서로 피드백이 더 활발해지는 시기이지 않을까 싶습니다. 혹시 이번 주까지 개발이 가능할까요?
> 
> @kimboyhood 조금더 설명해주실수 있을까요? 지금 #HELP 쓰는 것에 어떤 시각적 효과가 추가되어야 하나요?

지금 메이커들이 문서 가장 상단에 버터를 추가하는 법을 작성해서 버터 추가를 독려하고 있는데요. 경우에 따라 버터 추가를 본문 어디에 해야할 지 모호한 경우가 있는 것 같아요. 운영진이 버터가 필요해보이는 목차에 #HELP를 표시하는 방법으로 좀 더 가이드를 해주면 어떨까 싶습니다. 제 생각으로는 다른 마크다운문법처럼 #HELP 태그에 스타일을 입혀주시는 정도면 어떨까 하는 생각이 드네요.

**Comment by iamswain25** [comment]
@kimboyhood 막상 스타일 입히려니 어떻게 입혀야 할지 모르겠어요... 제가 디자인이 젬병이라서 ㅠㅠ 혹시 원하시는 스타일이나 기능이 있으시면 레퍼런스 주시면 감사하겠습니다.

**Comment by dalikim** [comment]
> @kimboyhood 막상 스타일 입히려니 어떻게 입혀야 할지 모르겠어요... 제가 디자인이 젬병이라서 ㅠㅠ 혹시 원하시는 스타일이나 기능이 있으시면 레퍼런스 주시면 감사하겠습니다.

이건 제가 오늘 레셈님과 이야기해서 휙 입혀 놓을께요. ^^

**Comment by iamswain25** [comment]
@dalikim 소년님과 통화해서 제가 처리하기로 했습니다.
