### ISSUE TITLE
버터보드 '전체화면에서 작성' 시 에디터 화면과 미리보기 화면 씽크 맞추기

### ISSUE THREAD

**Issue by boyhood-parti** [parti-coop/demosx-buttercon#75]
버터보드 '전체화면에서 작성' 시 에디터 화면과 미리보기 화면의 스크롤이 서로 달라 현재 편집 중인 본문을 미리보기 화면에서 볼 수 없다는 문의가 들어왔습니다. 저의 추측으로는 버터보드의 내용이 일정 분량 이상으로 늘어나는 경우 발생하는 문제인 것 같아요. @iamswain25 

https://butterknifecrew.kr/butter-edit.do?id=157 여성 1인가구 행복타운 보드에서 발생한 이슈 입니다.
ex) 국제인권조약 부분을 편집 중이나, 미리보기 화면에서는 긴급복지 지원법 부분이 보임.\
<img width="1280" alt="스크린샷 2019-11-18 오후 2 42 10" src="https://user-images.githubusercontent.com/53370999/69027383-1a96c900-0a12-11ea-9de1-23733db384bb.png">

**Comment by iamswain25** [comment]
@kimboyhood 오픈소스를 까서 해결해보려고 했는데, 생각보다 어렵네요. 당장 할 수 있는건 같이 스크롤 되지 않고, 따로 스크롤 하는겁니다. 그럴 경우 다른 분들이 쓰기 불편해 할까 걱정되네요.

**Comment by boyhood-parti** [comment]
> @kimboyhood 오픈소스를 까서 해결해보려고 했는데, 생각보다 어렵네요. 당장 할 수 있는건 같이 스크롤 되지 않고, 따로 스크롤 하는겁니다. 그럴 경우 다른 분들이 쓰기 불편해 할까 걱정되네요.

말씀하신대로 따로 스크롤 하는 것은 다른 팀들이 불편해질 것 같네요. 우선 해당 보드의 팀에게 눈 모양 아이콘(미리보기) 기능을 안내해 드리는 것으로 해결하겠습니다.
