### ISSUE TITLE
팀 명 필드 추가

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#79]
기존 필드 재활용 하자

**Comment by dalikim** [comment]
팀 소개 필드까지 만들어야나요 ㅠㅜ

**Comment by iamswain25** [comment]
팀 소개는 없어지고 프로젝트 소개로 바뀌었네요. 팀 명 필드는 원래 넣었었는데 수정 페이지에 없어서 상단에 커밋된건 그거 고친것입니다.
