### ISSUE TITLE
버터보드 알림봇의 알림텍스트를 변경합니다.

### ISSUE THREAD

**Issue by boyhood-parti** [parti-coop/demosx-buttercon#82]
@iamswain25 @anne-parti 오프라인 회의에서 이런저런 대화를 하다가, '크루들이 서로의 버터추가에 더 감사표시를 하게 하려면 어떻게 해야할까?'에 대해 의견이 나왔는데요. 지금 버터가 추가될 때마다 슬랙으로 가는 버터알림봇 문구를 수정해보면 어떨까요?

기존
> - 버터 수정: <버터보드명> | <요약> 
> - ex) 버터 수정: 유급병가 의무화 추진 제안 | 대상자 수정 및 당사자 사례 수정

수정 제안
> - <크루명> 님이 <요약> 버터를 추가했어요. | 버터를 더해준 크루에게 감사 인사를 전해보세요.
> - ex) 소년_김지수 님이 대상자 수정 및 당사자 사례 수정 버터를 추가했어요. | 버터를 더해준 크루에게 감사 인사를 전해보세요.

**Comment by iamswain25** [comment]
@kimboyhood 깃헙 알람이 하도 많이 와서 놓쳤었네요 ㅜ 제안 주신데로 작업해볼게요.

다만 슬랙도 마크다운이라 제안주신 문구의 링크를 어떻게 달아야 할지 보여 주시면 좋겠어요.
현재는: 아래 양식에서 <버터보드명>을 클릭하면 버터 상세화면으로 가고, <요약>을 클릭하면 변경 비교 화면으로 갑니다.

버터 수정: [**[가이드] 정책 제안 점검 체크리스트**](https://butterknifecrew.kr/butter.do?id=146)
> [직장평평이팀 버터보드 이름이 바뀌어서 수정했습니다](https://butterknifecrew.kr/butter-history.do?id=658)

**Comment by boyhood-parti** [comment]
> @kimboyhood 깃헙 알람이 하도 많이 와서 놓쳤었네요 ㅜ 제안 주신데로 작업해볼게요.
> 
> 다만 슬랙도 마크다운이라 제안주신 문구의 링크를 어떻게 달아야 할지 보여 주시면 좋겠어요.
> 현재는: 아래 양식에서 <버터보드명>을 클릭하면 버터 상세화면으로 가고, <요약>을 클릭하면 변경 비교 화면으로 갑니다.
> 
> 버터 수정: [**[가이드] 정책 제안 점검 체크리스트**](https://butterknifecrew.kr/butter.do?id=146)
> 
> > [직장평평이팀 버터보드 이름이 바뀌어서 수정했습니다](https://butterknifecrew.kr/butter-history.do?id=658)

첫 문장은 변경비교화면, 뒷 문장은 해당보드의 댓글로 갈 수 있을까요? 더 욕심내자면 댓글 입력창에 해당 크루가 멘션되어 있으면 좋을 것 같아요. @소년_김지수 처럼요.

**Comment by iamswain25** [comment]
**소년_김지수** 님이 _대상자 수정 및 당사자 사례 수정_ 버터를 추가했어요. 
> 버터를 더해준 크루에게 감사 인사를 전해보세요.

최대한 구현해보겠습니다 ㅎㅎ @kimboyhood 양식은 이 정도로 할게요.

**Comment by iamswain25** [comment]
버터보드 끝나고 나서야 적용을 했네요...
