### ISSUE TITLE
로그인 하지 않아도 공감 버튼 클릭 가능

### ISSUE THREAD

**Issue by iamswain25** [parti-coop/demosx-buttercon#88]
어떻게 막을까는 더 고민
IP로 막나?
시간으로 막나?

**Comment by iamswain25** [comment]
쿠키로 문서 아이디 넣어 처리 예정

**Comment by iamswain25** [comment]
급하지 않아서 문제 제기시 처리

**Comment by anne-parti** [comment]
@iamswain25 
로그인 하지 않은 상태에서 공감 버튼 동작하는건 확인 했구요. 
일단 닫아둘게요 필요시에 다시 열어주세요. (추후논의 라벨 만들어서 달아둡니다~)
