### ISSUE TITLE
버터보드에서 표가 제대로 표시되지 않습니다.

### ISSUE THREAD

**Issue by boyhood-parti** [parti-coop/demosx-buttercon#92]
https://butterknifecrew.kr/butter.do?id=146 보드에 작성된 표가 미리보기에서는 제대로 보이지만, 실제 보드에서는 제대로 표시되지 않고 있네요.

**Comment by iamswain25** [comment]
저도 배포하고 확인하니 #help 적용한 후에 나는 버그인것 같아요 ㅜ 빨리 잡아보겠습니다.

**Comment by iamswain25** [comment]
@kimboyhood 확인하니 소스는 문제가 없었는데, 빌드가 제대로 되지 않았네요. 다시 원복시켰습니다!
https://butterknifecrew.kr/butter.do?id=146
