### ISSUE TITLE
문화살롱 - 카테고리(분야) 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#93]
문화살롱 카테고리(분야)를 수정해주세요. 
현재 작성 페이지에 해당 항목이 '살롱 주제'로 되어있고, 선택 목록이 아이디어 페이지의 살롱 주제로 뜹니다. 

작성 페이지 레이블은 '분야' 로 선택 목록은 아래와 같이 추가 부탁드립니다. 
- 전체
- 가족
- 건강
- 대중문화
- 성인지교육
- 일
- 주거
- 지역

**Comment by iamswain25** [comment]
문화살롱과 아이디어 카테고리 같이 쓰기로 함

**Comment by anne-parti** [comment]
실서버에 세팅했습니다.
