### ISSUE TITLE
문화살롱 - (PC버전) 공유하기 버튼 수정

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#96]
1. 트위터로 공유 시 '버터공유' 가 추가되는데 의도된건가요? 
2. 'url복사' → 'URL 복사'로 레이블 변경 후 우측 이모티콘 제거해주세요.

**Comment by iamswain25** [comment]
@anne-parti 텍스트를 하나 넣을   수 있게 되어 있어서 "버터공유" 간단하게 추가했어요. 빼고 url만 갈까요?

**Comment by anne-parti** [comment]
@iamswain25 버터공유라고 되어있어서 버터보드에서 가져온건줄 알았어요. 다시 보니까 버터보드에는 공유 버튼이 없네요. 빼는게 좋을 것 같아요. 뒤에 해시태그는 좋습니다.
