### ISSUE TITLE
문화살롱 - (PC버전) 상세 페이지 목차

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/demosx-buttercon#97]
1. 상세 페이지 좌측 목차 섹션을 스크롤과 상관 없이 고정해서 보여줄 수 있나요? 
목차에서 선택 시 다시 목차 보려면 스크롤 올려야하는 게 조금 불편합니다. 
참고: https://100up.kakaoimpact.org/problems/30/view

2. 목차 목록 간 간격, 본문과의 간격을 수정해주세요. https://zpl.io/br0gO73

**Comment by iamswain25** [comment]
@anne-parti 
1. 저도 처음 개발할 때 스크롤 해야지 시도 하다가 포기했어요. 기초공사를 처음부터 다시해야해서요 ㅜㅜ
